# Documentation at 
# https://jekyllrb.com/docs/configuration/options/

baseurl: /

exclude: ["readme.md", "LICENSE", "cfp/*_cfp.md"]

email: m.kirkedal@di.ku.dk

description: >- # this means to ignore newlines until "baseurl:"
  Website for the Reversible Computation conference, bringing together computer science, mathematics, engineering, and physics on the topic of reversible computation.

github_username:  reversible-computation

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
